name: "Run systests on emulator"
on:
  pull_request:
    branches:
      - [main, master]

jobs:

  run-system-tests:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install / run Nox
      run: |
        python -m pip install --upgrade setuptools pip
        python -m pip install nox
        nox -s system
